version: '3'
services:
    db:
        image: mariadb
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        volumes:
            - blog_db:/var/lib/mysql
        networks:
            - blog
            - default

    app:
        build:
            context: .
            dockerfile: docker/Dockerfile.app
        depends_on:
            - db
        volumes:
            - ./:/var/www/
        networks:
            - blog

    web:
        image: nginx:1.17-alpine
        depends_on:
            - app
        ports:
            - 80:80
            # Use for ssl
            # - 443:443
        volumes:
            # Path where save ssl key
            # - Cert_KEY_Path:/etc/nginx/ssl:ro
            - ./public:/var/www/public
            - ./logs:/var/log/nginx
            - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - blog

networks:
    default:
    blog:
        external:
            name: laravel-blog

volumes:
    blog_db: